### PR TITLE
No wait for each interval

### PR DESCRIPTION
**Pull request by obando777**

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Thank you for this! I am going to review and discuss it on stream next time. I have checked it out and tested it locally and it works!

**Comment by obando777** [comment]
> Thank you for this! I am going to review and discuss it on stream next time. I have checked it out and tested it locally and it works!

thanks for checking it out

**Comment by whitep4nth3r** [comment]
Hey hey! Sorry, I did some more refactoring today and completely forgot to look at your PR! Please forgive me! If you want to merge in the current master and see if anything is still relevant that you want to add then please feel free. I am going to add you as a contributor as well for the ideas. Thank you!

**Comment by whitep4nth3r** [comment]
@all-contributors please add @obando777 for Code

**Comment by obando777** [comment]
not a problem i just merge your master against the PR, let me know if anything else comes out

**Comment by obando777** [comment]
@whitep4nth3r u__u i did change a lot this sorry bother this much

**Comment by whitep4nth3r** [comment]
Hey! Thank you for this! It looks interesting. It would be great if you could explain the benefits of the asyncLock so I could understand it better? Also +1 for the test!

**Comment by obando777** [comment]
well with that you could resolve any ball as soon as function ball rolls gets available without a wait interval in between calls

**Comment by whitep4nth3r** [comment]
Another member of the community submitted a similar pull request - I am going to accept that PR due to the code having more explanation around it and it resonating better with me. Regardless, you are added as a contributor in the docs - thank you for your contributions!

**Pull request closed without merging**
